# Generated by Django 4.2.5 on 2024-07-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7, unique=True),
        ),
    ]
