# Generated by Django 4.2.5 on 2024-07-12 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
