# Generated by Django 4.2.5 on 2024-07-13 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_customuser_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='color',
        ),
    ]
