# Generated by Django 4.2.5 on 2024-07-13 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
    ]
