# Generated by Django 4.2.5 on 2024-07-14 11:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_rename_name_contact_first_name_contact_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
