# Generated by Django 4.2.5 on 2024-07-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(default='John', max_length=200),
        ),
    ]
