# Generated by Django 4.2.5 on 2024-07-14 14:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_remove_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
