# Generated by Django 4.2.5 on 2024-07-14 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0033_task_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='contacts',
        ),
    ]
