# Generated by Django 4.2.5 on 2024-07-14 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0034_remove_task_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
    ]
