# Generated by Django 4.2.5 on 2024-07-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0035_remove_task_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
