# Generated by Django 4.2.5 on 2024-07-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0037_task_assigned_to_task_contacts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
    ]
