# Generated by Django 4.2.5 on 2024-07-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0039_remove_customuser_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7, unique=True),
        ),
    ]
