# Generated by Django 4.2.5 on 2024-07-16 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0043_alter_contact_color_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
