# Generated by Django 4.2.5 on 2024-08-15 07:47

from django.db import migrations
from django.contrib.auth import get_user_model

def create_guest_user(apps, schema_editor):
    User = get_user_model()
    guest_email = 'guest@example.com'
    guest_password = 'guestpassword'
    
    if not User.objects.filter(email=guest_email).exists():
        User.objects.create_user(
            email=guest_email,
            password=guest_password,
            first_name='Guest',
            last_name='User',
            username='guest_user',
            color='#FFD700'  # Eine Farbe für den Gast
        )

class Migration(migrations.Migration):

    dependencies = [
        # Setze hier die Abhängigkeit zu deiner letzten Migration
        ('tasks', '0048_alter_customuser_color'),
    ]

    operations = [
        migrations.RunPython(create_guest_user),
    ]
