# Generated by Django 4.2.5 on 2024-08-18 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0051_remove_notification_user_notification_contacts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
    ]
